micronaut:
  application:
    name: byte-buddy
  server:
    port: 8080
    thread-selection: AUTO
    netty:
      access-logger:
        enabled: true
        exclusions:
          - /health
          - /prometheus
  security:
    enabled: true
    endpoints:
      login:
        enabled: false
      oauth:
        enabled: false
    token:
      jwt:
        signatures:
          jwks:
            keycloak:
              url: https://auth.blackforrestdevelopment.de/realms/board-buddy/protocol/openid-connect/certs
    intercept-url-map:
      - access: isAnonymous()
        pattern: /swagger/**
      - access: isAnonymous()
        pattern: /swagger-ui/**
      - access: isAnonymous()
        pattern: /img/**
      - access: isAuthenticated()
        pattern: /**
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
      img:
        paths: classpath:static/img
        mapping: /img/**



datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    schema-generate: NONE
    dialect: POSTGRES
    schema: board_buddy

jackson:
  serialization-inclusion: ALWAYS

flyway:
  datasources:
    default:
      enabled: true
      default-schema: board_buddy
      create-schemas: true
      schemas: board_buddy
      clean-schema: false
